# Generated by Django 3.1.3 on 2024-05-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_auto_20240516_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelloWorld',
        ),
    ]
